<?php

// Example input data (replace this with your actual map lines):
$dat = [
    "RRRRIICCFF",
    "RRRRIICCCF",
    "VVRRRCCFFF",
    "VVRCCCJFFF",
    "VVVVCJJCFE",
    "VVIVCCJJEE",
    "VVIIICJJEE",
    "MIIIIIJJEE",
    "MIIISIJEEE",
    "MMMISSJEEE",
];

$dat = [
	"CCCCCCCCCCKKKKKKKKDKQQQQQQQQFFRFFFFEEEEEEEEEEEEEEEEUUUUUUUBBBBBBBBBBBBBBBBBXXXXXXXXXTTNTTTTTTTTTTTTTTTTTTTTTTXXXXXXXRRRRRRRRRRRRRRRRRRMYYYYY",
"CCCCCCCCCKKKKKKKKDDKKQQQQQQQFFFFFFEEEEEEEEEEEEEEEEEUEUUUUUJBBBBBBBBBBBBBBBBBXXXXXXXXTTTTTTTTTTTTTTTTTTTTTTTTTXXXXXXXRXRRRRRRRRRRRRRRRPYYYYYY",
"CCCCCCCCKKKKKKKKKKKKKQQQQQQFFFFFFFFFFEEEEEEEEEEEEEEEUUUUUUUBBBBBBBBBBBBBBBBBXXXXXDXXXXXTTTTNNNNTTTTTTTTTTTTYYTXXXXXXXXRRRRRRRRRRRRRRRYYYYYYY",
"CCCCXXXKKKKKKKKKKKKKKQQQQQQFFFFFFFFFFEEEEEEEEEYYYEEEEUUUCUUMBBBBBBBBBBBBBBBBXXXXXDXXXXXTTTCCNNNNNTTTTTTTTTTTTTXXXXXXXRRRRRRRRRRRRRRRRSYYYYYY",
"CCXXXXXXHKKKKKKKKKKKKKKQQFFFFFFFFFFFFFFEEEEEEEYYYEEEEEEMMMMMBBBBBBBBBBBBBBBXXXXXDDDXXXXTTCCNNNNNTTTTTTTTTTTTXTXXXXXXXRRRRRRRQRRRRRRRKYYYYYYY",
"CCXXXXXXHKKKKKKKKKKKKKQQQFFFFFFFFFFFFFFEEEEEEEYYYYYYEEEMMMMMMMMBMMBBBBBBBBXXXXXXDDEDDXXTTNNNNNNNTTTTTTTTTTTTXXXXXXXXRRRRRRRRRRRRRRRRKYYYYYYY",
"XXXXXXXXXKKKKKKKKKKKKKFFFFFFFFFFFFFFFFFFEEEEEEEYYYYYYEEEMMMMMMMMMMBBBGZBBXXXXXXDDDDDDDDTTTNNNNNNTTTTTTTTTVTXXXXXXXXXXRRXXRRRRSSRRRSRKKYYYYYY",
"TXXXXXXXBKKKKKKKKKKKKDDDFFFFFFFFFFFFFFFFEEKKEEYYYYYYYYYMMMMMMMMMMMBBBZZZQZXXXDDDDDDDDDDTTTNXNNNNNTTTTTTTTVXXXXXXXXXXXXXXXRRSRSRRSRSSYYYYYYYY",
"XXXXXXXXXKKKKKKKKKKKKKDDDFFFAFFFFFFFFFFFKKMKKEYYYYYYYYMMMMLLLLMMMBBBBCZZZZZZZDDDDDDDDDDTTTNNNNNNNTTTTTTTTVVVXXXXXXXXXXXXRRSSSSRSSGSSSSYYYYYY",
"GXXXXXXXXKKKKKKKKKKKKKKDFFFAAAAFFFFFFFKKKKKKKYYYYYYYYYMMMMLLLLMMMBBBCCZZZZZZZDDDDDDDDDDQQQQQQQNQQTTLTTVVVVXXXXXXXXXXXXXRRRRSSSSSGGSSSSYYYYYY",
"GXXXXXXXGGKKKRKKKKKKKKKKEBBAAAAAFFFFFKKKKKKKKKYYYYYYYYMMMMLLLLMMMMBZZZZZZZZZZDDDDDDDDDDQQQQQQQQQQQQQVVVVVCCCKCCXXXXXXXXRRRRSSSSSSGGGSSYYYYYY",
"GXXXPXXXGGGKRRRRKKKKKKKBBBAAAAAAYAAFFKKKKKKKKKKKYYYYYYMLMMLLLLMMMMNZZZZZZZZZZDHHDDDDDDDPPPQQQQQQQQQQQQQVVVCCCCCCXXXXXXXEPRSSSSSSSSGGSSSYYYYY",
"GGXXXGGGGGHKPRRRRRRJKBBBBBAAAAAAAAAAXKJKKKKKKYYYYYYYYYYMMMLLLLMLLLLLLLLLLZZZZZHHHDDDDYYYPPQPPPQQQQQQQQVVVVVVCCCXXXXXXEEEEEESSSSGGGGGGGSYYYPP",
"GGGGGGGGGGGBGGRRRRRBBBBBBBAAAAAAAAAAAAJKKKKKKKYYYYBBBYYMMMLLLLMLLLLLLLLLLZZZHHHHHHDDYYYYYPPPPPPQQQQQQQQVVVVVVCXXXXXXEEEEEESSSGGGGGGGGGGPPPPP",
"GGGGGGGGGGGBGRRRRRRRBBBBBBAAAAAAAAAAAAYKKKKBBBBBBBBBOYMMMMLLLLMLLLLLLLLLLLLZHHHHHHPYYYPPPPPPPPPQQQQQQQQVVVVVCCCXXXEEEEEEEEEGGGGGGGGGGGGGPPPP",
"GGGGGGGGGGGGGGRRRRRRBBBBBBWAAAAAAAAAAAYYKKBBBBBBBBBBBBMLLLLLLLELLLLLLLLLLLLZZHHHHHPPPPPPPPPPPPPPQQQQQQQQQVVVVGGGXXXEEEEEEEEEEOGGGGGGGGGPPPPP",
"GGGGGGGGGGGGRRRRRRRBBBBBBAAAAAAAAAAAAAAYKKBBBBBBBBBBBBBLLLLLLLLLLLLLLLLLLLLZZHHHHHHPPPPPPPPPPPPAQQQQVVVVVVVVGGGOXGIEEEEEEEEEEEEGGKGGGGOOPPPP",
"GGGGGGGGGGGGRRRRRRBBBBBBBBAAAAAAAAAAAAYYKYBBBBBBBBBBBBBLLLLLLLLLLLLLLLLLLLLZZHHHHHHPPPPPPPPPAAAAQQQVVVVVVVVGGGGGGGEEEEEEEEEEEEEGKKGGGGOOPPPP",
"GGGGGGGGGGGRRRRRRRBBBBBBAAAAAAAAAAAAAAYYYYYBBBBBBBBBBBBLLLLLLLLLLLLLLLLLLZZZHHLLHPHPPZPPPPPAAAAAQVVVVVVVVVVVGGGGGGEEEEEEEEEEEEEGVKGGGGOGPPPP",
"GGGGGGGGGZRRRRRRRBBBBBBBBBBBBAAAAAAAAAYYYYYBBBBBBBBBBBBLLLLLLLLLLLLLLLLLLZZHHLLLHPPPPZVVXPPAAAAQQVVVVVVVVVGGGGGGGGGEEEEEEEVVEEEVVVGGGGGGPPCC",
"GGGGGGGGGZRRRRRRRBBBBBBBBBBBBAAAAAAHAAAAYYBBBBBBBBBBBBBBLLLLLLLLLLLLLLLLLJHHHLLLLLPPPVPVVVVAAAAQVVVVVVVVVVGGGGGGGGGEEEEEEEEVVVVVVVGCCCGCCCCC",
"GGGGGGGGGZRRRRRRBNBBBBBBBBBBBAAAAAAHIAAYYYBBBBBBBBBBBBAALLLLLLLLLLLLLLLLLJJJLLLLLLLNNVVVVVVAVVVQAAVVVVVVVVGGGGGGGGGVVVVVVVVVVVVVVVGCCCCCCCCC",
"GGGGZGGZGZZRRRRRBBBBBBIIIBBIIIIIIIIIIYYYBBBBBBBBBBBBBBABLLLLLLLLLDDZZDDJJJJJLLLLLLLNNVVVVVSVVVBBVAVVVVVVVGGGGGGGGGVVVVVVVVVVVVVVVVVVCCCCCCCC",
"GGGGZZZZZZZRRRRZZBHBBBBBIBIIIIIIIIIIIIYYYYHHBBBBBBBBBBBBLLLLLLLLLDDDDDDDDDDDLLLLLLLLLQVVVVVVVVVVVVVVVVVVVVGGGGGGGGGGVVVVVVVVVVVVVVVVVCCCCCCC",
"QQZZZQZZZZZZZZZZZBBBBBBIIIIIIIIIIIIIIYRRRRRRRRRRBMBBBIBBLLLLLLLLLDDTTDDDDDDDLLLLLLOOLVVVVVVVVVVRRRVVVVVVVVGGGGGOGOOGGGGVVVVVVVVVVVVVVCCCCCCC",
"QQQQQQZZZZZZZSZZZBBBBBBIQIIIIIIIIIIIIYRRRRRRRRRRMMGGGAAALLLLLLLLLTTTTTDDTDDDDLLLLLOOOOVVVVVVVVENNNUUUVVVVVGGJGGOOOOGGGGGGBBBVVVVVVVVVCCCCHCC",
"QQQQQQQZZZZZZSZZZBBBBBBDIIIIIIIIIIIIIIRRRRRRRRRRGMGGGAAAAAAAAAAATTTTTTTTTTTDDDLLLLLLOVVVLLVVVEENNNUUVVVVVJKGJJGOOOOOGGGGBBBBVVVVVVVVVVCHHHHH",
"QQQQQQQQZQZZSSZZZZBZBZBDIIIIIIIIIIIIIIRRRRRRRRRRGGGGAAAAAAAAAAAATTTTTTTTTTDDDLLLLLLLLVVVLLVVWWNNNNNWWFFVJJJJJJGOOOWOOGGGBBBBVVVVVVVVVVCHHHHH",
"QQQQQQQQQQZZSSZZZZZZZZSDDIIIIIIIIIIIIIRRRRRRRRRRGGGGGAGAAAAAAAAATTTTTTTTTTDDDLLLLLLLLLLLLWWWWWWWNNNNWWWJJJJJJJHHJOOOSWGGBBBBBBBVVVVVVVVHHHHH",
"QQQQQQQQQQZZSSSSSSSSSSSIIIIIIIIIIIIIIIRRRRRRRRRRKKKKKGGAAHAAAAAATTTTTTTTTTDDDLDHHLOLLLLLLWWWWWWWWWWWWWWHJJJJJJJJJJJJSWGWBBBBBBBBBVVLVVVHHHHH",
"QQQQQQQQQQQZSSSSSSSSSSSKKBIIIIIIIIIIIIRRRRRRRRRRKKKKKGGAGAAAAGAGTTTTTTTTTTDDDDDHHHOLLLLLLLWWWWWWWWWWWWWWWJJJJJJJJWWWWWWWWBBBBBBBBBLLVKVHHHHH",
"QQQQQQQQQQQZSSSSSSSSSSSKKBBIKIKKKIIIIIRRRRRRRRRRKKKKKGGGGGGGGGGGTTTTTTTTTTDDDDDDHHOLLLLLLLWWWWWWWWWWWWWWWFJJJJJJJJWWWWWWWWWBBBBBBBLLVRRHHHHH",
"QQQQQQQQQQQQSSSSSSSSSSSKKKBKKKKKKKFIFFRRRRRRRRRRKKKKKGGGGGGGGGGGIITTTTTTTTDDDDDDDDOOOLOOLLWWWWWWWWWWWWWWWFJJJJJJJWJWWWWWWWWBBBBBBBLLVRRHHHHH",
"QQQQQQQQQQQQQQRSSSSSSSSKKKKKKKKKKKFFFFRRRRRRRRRRRKKKKGGGGGGGGGGGIIITTTTTTDDDDXXDOOOOPOOLLLLWWWWWWWWWWWWWFFFFFFJJWWWWWWWWWWWWWBBBBBRRRRRHHHHH",
"QQQQQQQQQQQQQUSSSSSSSSSKKKKKKKBFFFFFFFFFRKRRRRRRRKKKKGGGGGGGGGGGGGGGGGTTGGDDDCCOOOOOOOOOOLLLWWWWWWWFWWWWWFFFFFFJJCWWOWWWWWWWWBBBBBRRRRRRRHHH",
"QQQQQQQQQQQQQUUSSSSSSSSKKKKKKKKKKFFFFFFFRKRRRRRRRKKKKGRRRGGGGGGGGGGGGGGGGGGDCCCCOOOOOOLLLLLLLWWWWWWWWWWWFFFFFFFCCCWWWWWWWWWWWBBBBRRRRRRRRHHH",
"OQQQEQNQQQQQQUDDSSSSSSSIKKKKKKKKKFFFFFFFNKRRRRRRRKKKKGRRRRRRGGGGGGGGGGGGGGGDDCCOOOOOOOLPPPLPLWWWWWWWWWWWWFFJJFWWWWGWWWWWWWTWRRBRRRRRRRRRHHHH",
"OEEQEEQQQQQQQUUDSWSSSIIIKKKKKKKFFFFFFFNNNKRRRRRRRKGGGGGRRRRRRGGRGGGGGGGGGGICCCOOOOOOOOOPPPPPPWWWWWWWWWWWFFFJJFWWWGGGWWWWWWWRRRRUURRRMRFRRHHR",
"EEEEEEQQQQQQQUDDDDDDDIKKKIKKKKKFFFFFFNNNNKRRRRRRRKGGGGGRDDRRRRGRRRGGGGGGGGGCCCOOOOOOOOPPPPPPPPWPPPWWWWWWWJJJWWWWWGGGWWWLWWUUUUUURRRMMRRRORRR",
"EEEEEEEQOQEEQQDDDDDDIIIKKIIIIKKKFFFFFNNNNNNNHSSSSGGGDDDDDJRRRRGGRGGGGGGGGGGGCCPCCOOOOPPPPPPPPPPPPRWWWWWWJJJWWWWWWGGGOWWLWOUUUUUUUUUMMRRRRRRR",
"IIEEEEEEEEEQDDDDDDHIIIKKIIIIIIKKYFFFFNWWNNHNHSSSSSGGDDDDDDDRRRGRRGGGGGGGGGGMCCCCCOOUUUPPPPPPPPPPPRWWMWJWJJJWWWWWWGGOOOOOOOOOUUUUUUUUURRRRRRR",
"IIEEEEEEEEEQDDDDDDHHHIIKIIIIIIIWWFFWWNWRHNHHHSSSSSGGGADDDDDDRRRRRRGGGGGGGRGGCCCCCCUUUPPPPPPPPPPPPPRWMMJJJWWWWWWWWWOOOOOOOOOOOUUUUUUUURRRRRRR",
"IIEEEEEEEEEDDDDDDDDHHIIIIIIIIIIWWFFWWWWWHHHHHHHSSSSSDDDDDDRRRRRRRRGGGGGGGRCCCCCCCCCCPPPPPPPPPPPPPEMWMJJLWWWWWWWRWOOOOOOOOOOOUUUUUUUUURRRRRRR",
"IXXGEEEEEEEXDDDDDDDHHIIIIIIIIIIIWWFWWWWKHHHHHHHHSSSDDDDDDDDDDDRRGGGGOGGGGCCCCCCCCCCPPPPPPPPPPPPPPPMMMJJLMMWWWBBEEOOOOOOOOOOOUUUUUUUURRRRRRRR",
"IXXXEEEEEEEXDDXXDDDHHQQIIQQQOOOOOOFWWWWHHHHHHHHHSDDDDDDDDDDDDDRRGGGGGEEECCCNCCCCCCCCPPPPPPPPPPBPPMMMMMJLLLLWRRBEEEEEOOMOOOOOUUUUUUUUURRRRRRR",
"IXXXXEEEEEEXXDXXXUDDQQIIQQQQOOOOOOWWWWWHHHHHHHHXDDDDDDDDDDDDDDRRRGGGGEEEECCCCCCCCCCCPPPPPPPPPPBPPMMMGGLLLLLRRREEEEEEEOOOOOOUUUUUUUUURRRRRRRR",
"IXXXXEEEXXXXXXXXUUDQQQIIQQQQOOOOOOWWWWWHHHHHHHHDDDDDDDDDDDDDDDREGGGGEEEEEECCCCTCCCCCCCCCCPPFPWMMMMMMGGGLLLLREEEEEEEOOOOOOOOUUUUUUUUURRRRRRRR",
"IIXXXXXEEXXXXXUUUUQQQQQQQQQQQQQQXHTWWWHHHHHHHHDDDDDDDDDDDDDDDRREIEEEEEEENEETTTTCCCCCCCCCPPPCWWMMMMMMMLLLLLMMEEEEEEEOOOOOHOOUUUUUUUURRRRRRRRR",
"IIIXXXXXEXXXXXUUXXXQQQQQQQQQQQQXXHTWWWHHHHHHHHHDDDDDDDDDDDDDRRREEEEEEEEENNETTTTCCCCCCCCCCCPCCCMMMMMMMMLMLMQMEEEEEEEHOHOHHHOUUUUUUUURRRRRRRRR",
"IKIKKKXXXXXXXXUUUXUUQQQQQQQQQQQHHHWWHWWHHHHHQQKDDDDDDDDDDTTTEEEEEEEEEEENNNNNNTTTTCCCCCCCCCCCCCZMMMMMMMMMLMMMEEHEEEHHHHHHHOOOUHUHUUURRRRRRRRR",
"IKKKKXXXXXXXXXXUUUUUQQQQQQQQQQHHHHHHHHHHHVQQQQQNDDDDDDDDDDTTEEEEEEEEEEENNNNNTTTTTTTCCCCCCCCCCCCCMMMMMMMMMMMMEERRRERHHHHHHHHHHHUHUUUUUURRRRRR",
"IKXXXXXXXXXXXXXUUUUUQQQQQQQQQQQHHHHHHHHHHQQQQQQDDDDDDDDDDDTTEEEEEEEEEEENNNNNFTTTTTTTKKCCKCCCCCCCZMMMMMMMMMRRERRRRWRHHHHHHHHHHHUHHUUUUURRRRRR",
"IXXXXXXXXXXXXXXUUJQQQQQQQQQZZQHHHHHHHHHHJJJJJQQQDDDDDYDTTTTTEEELLLEEEEENNNNTTTTTTTKKKKKCKKCCCCCCZMMMMMMMMRRRRRRRRRRRHHHHHHHHHHHHHUURRRRRRRRR",
"XXXXXXXXXVVXXXVVJJQQQZZQQZQZZHHHHHHHHHHHHJJJJQQQQQQDDDYYYYYTFEELLLEEEENNNNNNNTTTKPKKKKKKKKCCCCZZZMUMMMMMMRRRRRRRRRRRHHHHHHHHHHHHHHHRRRRRRARR",
"XXXXXXXXXVVVVVVVJJJJJZZZZZZZHHHHHHHHHHHHHHQQQQQQQQQQQYYYYTTTUUUUULLLNNNNNNNTTTTKKKKKKKKKKKKCCCZZZZUMMMMMMRRRRRRRRRRRHHHHHHHHHHHHHRRRRRRAAAAA",
"XXXXXXXXXVVVVJVVJJJJJJJJZZZZHHHHHHHHHHHHHKKJQQKKQQQYYYYLYTTJJUUUUUULLLNNNNNNNTTKKKKKKKKKKKKKUCUZZZUUMMMMMRRRRRRRRRUHHHHHHHHHHHHHHHHARRRAAAAA",
"XTXXXXXVVVVVVJJJJJJJAJJJZJJZZHHHHHHHHHHLLKKKKKKKKQQQYLLLYYUJUUUUUULLNNNNNNNNNNNKKKKKKKKKKDKEUUUUUUUUMMMMMMMRRRRRRRUHHHHHHHHHHHHXHHHAAAAAAAAA",
"FXXQQQVVVVVVVVOJJJJJJJJJJJJJZHHHHHHHLLLLKKKKKKKKVQZLYLLLLYUUUUUUUUUNNNNNNNNNNNKKKKKKKKKKDDDUUUUUUQUSMMMMMMMMRGRRRRRQHHHHHHHHHHHXXHHAAAAAAAAA",
"FFXFQQQVVVVOOOOOOJJJJJJJJJJJHHHHHHHHLLKKKKKKKKKKVQZLLLLLLYUUUUUUUUUNNNNNNNNNNNNKKKKKKKKKUUUUUUUUUUUUMMMMMMMMMRRRQQQQHHHHHHHHHHXXXXHASAAAAAAA",
"FFFFFFFFVVVOOOOIOJJJJJJJJJJJJHHHHHHHLKKKKKKKKKKVVLLLLLLLLLLUUUUUUUUUBBBNNNNNNNKKKKKKKKKKKKUUUUUUUUUUTTMMMMMMMMRRRRQHHHHHHHHXXXXXXXHHAAAAAAAA",
"FFFFFFOOOYVOOOOJJJJJJJJJJJJJJHHHHLLLLKKKKKKKKKKVVLLLLLLLLLLUUUUUUBBUBNNNNNNNNWWWKKKXKKKKQQQUUUUUUUUUUMMMMMMMMRRRRRQQQHHHQQQXXXXXXXHNXXAAAAAA",
"FFFFFFOOOOOOOOYJJJJJJJJJJJJJJJLHLLLLLLKKKKKKKKKVVVLLLLLLLLLLLUUUUQQQBBBNNNNNNWWWWKKKKKXXXXXXXXXXUULLLLMMMQQQQQQQQQQQQQQQQQQXXXXXXXXNXXAAAAAA",
"FFFFFFFFOOOOJJJJJJJJJJJJJJJJJJLLLLLLKLLKKKKKKKVVVVLLLLLLLLLLLLUUUQQQQQBBBBBQQWWWWWKLLLXXXXXXXXXXUULLLLLMHHQEQQQQQQQQQQQQQQQQXQXXXXXXXXAAAAAA",
"FFFFFFOOOOOOJJJOJJJJJJJJJJJJLLLLLLLKKKKKKKKKKKVVVWEELLLLLLLLLLQQQQQQQGQBBBQQQWWLWLALLLXXXXXXXXXXUULELLEHHQQQQQQQQQQQQQQQQQQQQQXXXXXXXXXAAAAA",
"FFFFFFOOOOOOOOOOOJOJJJJJJJJJJJLLLLLLLLKKKKKKKLLLLWWWLLLLLLLLLLLQIIQQQQQQQQQQQWWLLLLLLLXXXXXXXXXXXXXXXXXXXHHHHHHHHHQQQQQQQQQQQQXXXXXXXXXXXAAA",
"FFFFFFBBOOOOOOOOOOOJJJJJJJJLJLLLLLLLLLLLKKKKKLLLEWWWEEEELLLLLLLLIQQQQQQQQQQLJLLLLLLLLLXXXXXXXXXXXXXXXXXXXHHHHHHHHHUQQQQQQQQXQQXXXXXXXXXAAAAA",
"FFBBBBBBBOOOOOOOOOOOJJJOJJJJJNNNNNLLLLLLKKKKKLLDEEEEEEELLLLLLLJJQQQQQQQQQQQLLLLLLLLLLLXXXXXXXXXXXXXXXXXXXHHHHHHHHHQQQQQQQQQXXMXXXXXXXXXAAAAA",
"FFBBBBBBBBOOOOOOOOOOOOOOOJJNNNNNNNLLLLLLLLLLLLLDDEEEEXXLLLLXXXXXXQQQQQQQQQQLLLLLLLLLLLXXXXXXXXXXXXXXXXXXXHHHHHHHHHUQQQQQQXXXXXXXXXXXXXAAAAAA",
"FFBBBBBBBBOOOOOOOOOOOONNONJJNNNNNNLLLLLLLLLLLDDDEEEEEXXLLXXXXXXXXXXQQQQQQQQLLLLLLLLLXXXXXXXXXUUXXXXXXXXXXHQHHHHHHHQQQQQQQXXXXXXXXXXXXXAAAAAA",
"FBBBBBBBBBOMMOOOOOOOONNNNNNNNNNNNNNLLLLYYLLLLDDDEEXEXXXXLLLXXXXXXXQQQQQQQQQLHLLLLLLLXXXXXXXXXUUXXXXXXXXXXQQHHUUUUUGGGGGQQXXXXXXXXXXXXXXXSAAA",
"BBBBBBBBBBBMMMOOOOOOONNNNNNNNNNNNLLLLLLYYLLLLDDDDXXXXXXXLLXXXXXNNQQQQQQQQGGGGLLLLLLLXXXXXXXXXUUXXXXXXXXXXHHHHHUUUUUGGMGGGGXXXXXXXXXSSSSSSSAA",
"BBBBBBBBBBMMMMMMMOOOOONNNNNNNNNNNNLLLLLLYYLLLLLDDXXXXXXXLXXXXXNNNNNNNQQGGGGGGGLLLLLRXXXXXXXXXUXXXXXXXXXXXHHHHHUHUUMMMMGWGGXXAXXXSSSSSSSSSSAA",
"BBBBBBBBBBMMMMMMMMOOOONNNNNNNNNNRNLLLYYYYYLLLDDDDDDXXXXXXXXXXXNNNNNNRQQGGGGGGGLLLLLLXXXXXXXXXUXXXXXXXXXXXHHHHHHHRUMMMGGGGGJGAAASSSSSSSSSSSAA",
"BBBBBBBBBBMMMMMMMMEEONNNNNNNNNNNNNLLYYYYYYLLLLDDDDDXXXXXXXXXXXNNNNNNNGGGGGGGGLLXIDDDXXXXXXXXXUXXXXXXXXXXHHHHHHHHMMMMMGGGGGGGGGASSSSSSSSSSSAA",
"BBBBBBBBBMMMMMMMEEEEOONNNNNNNNNNNNYYYYYYYLLLLQDDDDDDDXXCCCXXXXXNNYNNGGGGGGGGGGGXXXNDXXXXXXXXXSXXXXXXXXXXJHHHHHHIMMMMGGGGGGGGGAASSSSSSSSSSSAA",
"BBBBBBBBBBKMAMMMEEEEEONNNNNNNNNNNRRYYYYYYLLDDDDDDDDDDDDCCCCXXXXNNNNNGGGGGGGGGGGGXXNNXXXXXXXXXSXXXXXXXXXXJHHHHHHHXXXXXGGGGGGGGGGSSSSSSSSSSSVA",
"PPBBBBBBBBBAAAMMMEEEEEENNNNBBNNNNRRYYYYYYYYYDDDDDDDDDDCCCCCXXXNNNNNNNNNGGGGGGGXXXXXNXXXXXXXXXXXXXXXXXXXXNNHHHHXXXXXXXGGGGGYYGGGYSSSSSSSSSSVV",
"PBBBBBBBBBBMMMMMEEEEEEENNBNBBGRRRRRRRYYYYYYYYDDDDDDDDDCCCCFXXXXNNNNNNFGGGGXGGXXXXXXNNNPPPXXXXXXXXXXXXXXXHHHHHHHXXXXXXGGGGGGYGYYYSSSSSSSSSVVL",
"PPBBBBBBBEBUMMMEEEEEEBBQNBBBBBRRRRRRYYYYYYYYYDDDDDDDDDCCCCXXXXXXNNNNNXXXXXXGGGXXXXXXNPPPPXXXXXXXXJJJJJJJXHXHHHHXXXXCXGGGGCYYYYYYYSSSSSSSSVVL",
"BPBBBBBBBEEMMMEEEEEEEBBBNBBBBBBBRRRYYYYYYYYYYYDDDDDDDDDCCCCCCCXNNHHNNHHXXXXXXXXXXXPNNPPPPXXXXXXXXJJJNNJJXXXHHHXXXCCCCCCGGCCYCYYYSSSSSSSSSSVV",
"BBBBBBBBEEEEMEEEEEEEEXBBBBBBBBBRRRRYYYYYYYYYYYDDDDDDDDDCCCCCCCCNHHHHHHHXXXXXXXPXPPPPPPPPPXXXXXXXXJJNNNJXXXXXHXXXXCCCECCGGCCCCCYSSSSSSSSGSSSV",
"MBBBBBBKEEEEEEEEEEEEEEBBBBBBBBBRRRRYRYYYYYYYYYXDDDDDDDDDCCCCCCCHHHHHHHXXXXXXXXPPPPPPPPPPPXXXXXXXXJJNNNNXXXXXXXXXCCCCCCCCCCCCCYYSSSSSSSSSSVVV",
"MMMLLBKKKEEEEEEEEEEEEEEBBBBBBBBBRRRRRYYYYYYYXXDDDDDDDDDCCCCCCCCHHHHHHHHHHXXXXXPPPPPPPPPPPXXXXXXXXNNNNNNNNXXXXVVXCCCCCCCCCCCCCCCCSSSSSTSSVVVV",
"MMMLBBKKKEEEEEEEEEEEEEMBBBJBBBBBRRRRRRRYDYYERRYDDDDDDDDCCCCCCCCHHHHHHHNNXXXXXXPWWPPPPPPPPPPPPJJJNNNNNNNNXXXXXVVXXXXXXXXCCCCCCCTTTSSLSSSVVVVV",
"MMMMMKKEEEEEEEEEEEEEAAJBJJJJJJJJJRRRRRRRYYYRRRDDDDDDDVDCCCCCCXCHHHHHHHNXXXXXXXWWWWWPPPPPPPPJJJJJJNNNNNNNNNXXXVVXXXXXXXXCCCCCCCCLTTTLLVVVVVCC",
"MMMMMEKEEEEEEEEEEEEEEJJJJJJJJJJJRRRRRRRRYRYYRRDDDDDDDVVCCCCCXXXHHHHHHNNXXXXXXXWWWWWWWPPPPPPPJJJJJJNNNNNNLLVVVVVXXXXXXXXCCCCCCCLLLLLLVVVVCCCC",
"MMMMMEEEEEEIIIIIEEEEEJRJJJJJJJJJJJRRRRRRRRRRRRDYDDDDDCCCCCCCCXXHHHSHHNXXXXXXXWWWWWWWWPPPPPPPPPJJJJNNNNNNLLLVVVXXXXXXXXXCCCCCCLLLKLLLLVVCCCCC",
"MMMMMEEEIEIIIIIIEEEEJJJJJJJJJJJJJJJRRRRRRRRRRRRYDDDODDCCCCCXXXXXXXXXXWXXXXXXWWWWWWWWWPPPPPPPYYYJJJNNLNNLLLVVVVXXXXXXXXXCCCCCLLLLLLLKLLLCCCGC",
"MMMMMMEEIIIIIIIIEEEXXJJJJJJJJJJJJJJJRRRRRRRRRRRYYDDDCDCCCCCXXXXXXXXXXWXXXXXXWWWWWWWWWPPPPPPYYYYYYJJYLLLLLLVVVVXXXXXXXXXCCCCLLLLLLLLLFLCCCCCC",
"MMMMMMMMIIIIIIIIXXXXXXXXJJJJJJJJJJJRRRRRRRRRRRYYYYYYCCCCCXXXXXXXXXXXXWWWWXWWWWWWWWWWWPPPPYYYYYYYYYYYLLLLLLLVVVXXXXXXXCCCCCCCLLLLLLLLCCCCCCCC",
"MMMMMMMIIIIIIIIIIIXXXJJJJJJJJJHHJJJRRBBBBBBBBYYYYYYYCCCCCXXXXXXXXXXXWWWWWWWWMWMMMMMMMMPPYYYYYYYYYYZYLLLLLLLVVVXXXXXXXCCCCCCCCLSLLLLLLCCCCCCC",
"MMMMMMMMIIIIIIIIIIXXXJJJJJJJCHHJJJJRRBBBBBBBBYYYYYYCCCCCXXXXXXXXXXXXXWIIIIIWMMMMMMMMMMYYYYYYYYYYYYYYLLLLLLZVVVVVVVVVVVVVCCCCSSSLLLLLCCCCCCCC",
"MMMMMMMIIIIIIIIIIIXXICCCCCCCCHHHDRRRRBBBBBBBBYYYYYYYYCCCCCXXXXXXXXXXXDIIIQMWMMMMMMMMMMMYYYYYYYYYYYYYLZZZLZZZVVVVVVVVIVVVVCCCOOOLLLLCCCCCCCCC",
"MMMMMMIIIIIIIIIIIIIIICCCCCCCHHHDDDRRRBBBBBBBBYYYYYYYCCCCCCCCEEXXEXEEEWWWWQMMMMMMMMMMMMEYYYYYYYYYYYLLLZZZLZZZVVVVVVVVIIVVIIQQOOOLLLCCCCCCCCCC",
"MMMMMMMMIIIIIIIIIIIIICCZCCCQQHHDDDDDRBBBBBBBBYYYYYYYCCCCCCCEEEEXEEEEEWWWWMMMMMMMMMMMMEEEYYYYYYYYYYLLLZZZZZZYVVVVVVVVIIIIIIQOOOOOOLLCCCCCCCCC",
"HMMMMMMMMIIIIIIIIIIIIIZZZQCQQQQDDDXERBBBBBBBBYYYYYYYCCCCCCCEEEEEEEEEEEWMMMMMMMMMMMMMMEEYYYYYYYYYYYYLLZZZZZZQVVVVVVVVIIIIIIIIOOOOOOOOCCCCCCCC",
"MMMMMMMMIIIIIIIIIIIIIIZZZQQQQQQDEEEEEBBBBBBBBYYYYYYCCCCCCCCEEEEEEEEEWWWWMMMMMMMMMMMMMMMMYYYYYYYYYYYYLZZZZZZQPVVVVVVVBBIIIIIPOOOOOOOOCCCCCCCC",
"FMMMMMXMIIIIWIIIIIIIIIZZZQQQQQQEEEEEEBBBBBBBBBBBBBBCCCCCCCCEEEEEEEEEEWWWWWMMMMMMMMMMMMMSYYYYYYYYWWYYUZZZQQZQQVVVVVVVBIIWWWIIOOOOOOOOCCPCCCCC",
"FFFFMMXXXWIIWWIIIIIIIZZZQQQQQQEEEEEEEBBBBBBBBBBBBBBOOCCCCCCEEEEEEEEEFWWMMMMMMMMMMMMMZYYZSSSYYYYYYWWUUUUUUQQQQQVWWVVWWIWWWOOOOOOOOOOCCCPPPCPC",
"FFFFWWWWWWWWWWWIIIIIZZZZZQQQQQEEEEEZZBBBBBBBBBBBBBBOOOCCCCCCEEEEEEEEFWWKMMMMMMMMMMZZZZZZZSSYYYYYYWWUUUUEQQQQXXVWWVVWWWWWWWWOOOOOOOOOOOOPPPPP",
"FFFFFWWWWWWWWWWWIIIIZZZZQQQQZZEZZZZZZZBBBBBBBBBBBBBOOOCCCCCEEEEEEEEEEWWKKKMMMMMMZZZZZZZZZSSSYYYYWWWUUUUUQQQQQXXXWWWWWWWWWWWXOOOOFOOOOOOOOPPP",
"FFFFFWWWWWWWWWWWIZZZZZZZZZZZZZZZZZZZZOBBBBBBBBBBBBBXOCCCCCEEEEEEEEEEKWWWKKMMMMZZZZZZZZZZZZHHWWWAAAAAAAAQQQQQRQQWWWWWWWWWWWWWOOOFFFOOOOOOOPPP",
"FFFFFWWWWWWWWWWWPZZZZZZZZZZZZZZZZZZZPPBBBBBBBBBBBBBXXCCCCCCEEEEEEEKKKWKKKKMMMMMZZGZZZZZZZZCHWWWAAAAAAAAQQQQQQQQTTWWWWWWWWWWWOOOFFFFFFOOOOOOO",
"FFFFWWWWWWWWWWWWWZZZZZZJZZJJZZZZZZZPPPBBBBBBBBBBBBBXXCCCCCEEEEEEEKKKKKKKKKKMWWWWWGZZZZZZZZHHWWHAAAAAAAAQQQQQQQQTTWWSWWWWWWWWLLOFFFFFUUOOOOOO",
"GGFFFFWWWWWWWWWWWZZZZZJJJJJJZZJJJJZZPPPPPPBBBBBBBBBXXCCCCCEEJEEEEEEEKKVKKKWWWWWWWZZZZZZZZHHHHHHAAAAAAAAQQQQQQQQQTTTSWWWWWWWWLLOFFFFFUUOOOOGG",
"GGFFFFFWWWWWWWWWWXXZZZJOJJJJJJJJJJJJQPPPPPBBBBBBBBBMXCCCCCCCEEEEEEEEVVVVVWWWWWWWZZZZAAAAAAAAAAHAAAAAAAAQQQQQQQQQTSSSWWWWWWWLLLOLFFFUUUUUGGGG",
"GGGGFFFWWWWWWWWXWXXXXXJJJJJJYJJJJJJJPPPPPPBBBBBBBBBXXCCCVVCCEEVEEEEEVVVWWWWWWWWWWWZZAAAAAAAAAAHAAAAAAAAQQQQQQQQQQSSSWWWWWWWLLLLLFFFUUUGGGGGG",
"GGGGFFWWWWWWWWWXXXXJJJJJJJJJJJJJJJPPPPPPPPPPCPPPMMMMXXXXXVVVEEVVEVVVVVVJJWWWWWWWWZZZAAAAAAAAAAHAAAAAAAAQQQQQQQSSSSSSWWWWWWWLLHHFFFHHGGGGGGGG",
"GGGGGGIIIKKWWXWXXXJJJJJJJJJJJJJJJJPPPPPPPPPCCPPPMMMMXXXXVVVVVEVEEVVVVVVVVVVWWWWWQQQQAAAAAAAAAAHAAAAAAAAQQQUUUQSSSSNWWWWWWWWLHHHFFFHHHGGGGGGG",
"GGGGBGBIKKKKKXXXJXJJJJJJJJJJJJJJJJPPPPPPPPPCCPPMMMMYYYXVVVVVVVVVEVVVVVVVVVVWWWWWQQQQAAAAAAAAAAAAAAHHHAAHHHHHHHHHSSNNWWWWWWWWWHHHHHHHHKGGGGGG",
"GGGBBBBBBKKKKKXXJJJJJJJJJJJJJJJJJJJPPPPPPPPCCCCAMRMYYYXVVVVVVVVVVVVVVVVVVVWWWWWWQQQQAAAAAAAAAAAAHHHHHHHHHHHHHHHHNNNNNNWWWWWHWHHHHHHHKKKGGGGG",
"GGBBBBBBBBBKKKXXJJJJJJJJJJJJJEJJJJJPPPPPPPCCCCCCRRMYYYVVVVVVVVVVVVIIDDVVVVWWWWWWWQQQAAAAAAAAAAAAHHHHHHHHHHHHHHHHNNNNNNWHHHHHHHHHHHHHKKKGGGGG",
"GGGBBBBBBBBBBXXXXXJJJJJJJJJJJEEJJJJPPPPPPCCCCCCCXRRYYYNNNVVVVVVVVIIIDKVVVVKWWWQWWQQQQQQNNNHAAAAAHHHHHHHHHHHHHHHHNNNNNNWHHHHCCCHHHHHHKKKGGGGG",
"GGGGBBBBBBBBBXXXXJJJJJJJJJJJJJJSJJJPPPPPPPPCCCXXXRRYYYNNNNVVVVVVIIIFKKVVVVKSQQQQQQQQQNNNNNNAAAAAHHHHHHHHHHHHHHHHNNNNNNWWHHHCCHHHHHHKKGKGGGGG",
"GGGGGGBBBBBBBXXXXJJJJJJJJJJJJJJJPJJPPPPPPPPPCCXXXYYYYYYYYYVVVVVVGGVFKKVVVVKKKQQQQQQQQNNNNNAAAAAAHHHHHHHHHHHHHHHHNNNNNNWHHHHCCCHKHKHHKGGGGGGG",
"GGGBBBBBBBBBBBXXXXXXJJJJJJJJJJPPPPPPPPPWWWWWXXXXYYYYYYYYYNNVVVVVVVVKKKVKKKKIKKQQQQQQQQNNAAAAAAAAAAHHHHHHHHHHHHHHNNNNNNWHHCCCCCNKKKKKKKGGGGGG",
"DGDDBBCBBBBNNNNNXXXAAJAAAJFFFJPPPPPPPWWWWWWWXXXXYYYYYYYYYYYVVVVVVVVKKKKKKKKKKKKKQQQQQQQQAAAAAAAAAAHHHHHHHHHHHHHHYNNNNNNHHCCCCCNKKKKKKKGGGGGG",
"DDDYYBBBBBBJJNNEEAAAAAAAAAFFUFFVPPPPPWWWWWWLWXXXXYYYYYYYYYVVVVVVVVVVVVKKKKKKKKKKQQQQQQQQAAAANNNNNNHHHHHHHHHHHHHHYNNNNHHHHKCCCCCKKKKKKKGGGGGG",
"DDDDYYYBBDBJJJEEPPAAAAFAAAFFFFFVVVPPPQWWWWWWWXYYYYYYYYYYYZVVVVVVVVVVKKKKKKKKKKKKQQQQQAAQAANNNNNNNNHHHHHHHHHHHHHHYNNNNNKKHKKCCCKKKKKKKKLLGGGG",
"DDDDYYYDDDDDDDEEEEEAAAFFFFFFFFFFFVVPVWWWWWFWXXXYYYRYYYYNNVVVVVVVVVVVVKKKKKKKKKKKKQQQQAAAAANNNNNNNNHHHHHHHHHHHHHHYKNNNKKKKKKKCCKKKLLLLLLLLLGG",
"DDDDDDYDDDZDDDEEEEEIIFFFFFFFFFFFFVVPVVWWWWWHXXXXYYUYYNNNNVVVVVVVVVVVVVKKKKKKKKKKKKQQQAAAAANNNNNNNNHHHHHHHHHHHHHHKKNKKKKKKKKMKKKKKLLLLLLLLLLL",
"DDDDDDDDDDDDDEEEEEEIIFFFFFFFFFFFFVVVVWWWWWWXXXXXPPUUNNNNVVVVVVVVVVVVVVVKKKKKKKKKKKKKAAAAANNNNNNNNNHHHHTHHHHHHHHHKKKKKKKKKKKKVKKKLLLLLLLLLLLL",
"DDDDDDDDDDDDDEEEEEEEEFFFFFFFFFFFFVVVVWWWWWAAAXAUUUUUNNNNNNVVVVVVVVVVVVKKKKKKKKKKKKKAAAAAAANNNNNNNNHHHHTHHHHYYYYYKKKKKKKKKKKKKKKKKKLLLLLLLLLL",
"DDDDDDDDDDDDEEEEEEOOVFFFFFFFFFFFFFVVVVWVWWAAAAAUUUUUNNNNNNVVVVVVVVVVKKKKKKKWWKKKKKKKKAAAAANNNNNNNRHHHHTTTTTTYYYYKKKKKKKKKKKKKKKGKKKLLLLLLLLL",
"DDDDDDDDODOOEEEEEEOOOFWFFFFFFFFFFFVVVVVVWWAAAAUUUUUUNNNNNNLVVVVVVVVKKKKKKKWWWKKKKKAAAAAAAAAANNNNRRTTTTTTTTTYYYYYKYYKKKKKKKKKKKKKKKLLLLLLLLLL",
"DDDDDDOOOOOOEEEEEEOOOOFFFFFFFFFFVVVVVVLLOOLAAAUUUUDGNNNNNNNNVVVVVWRKKKKWWWWWWWWXXXAAAAAAAAAANNNNRRTTTTTTTTTYYYYYYYYYSSKKKKKKKKKKVLLLLLLLLLLL",
"DDDDOOOOOOOOEEEEEEOOOOFFFFFFFFFFVVVVVVLLLLLAAAAUQGGGNNNNNNNCCVTIVWRRKWKWWUWWWXXXXXAAAAAAAAAAUNNNNRTTTTTTTTTTYYYYYYYYSSKKKKKKKKKKLLLLLLLLLLLL",
"DDDDDDODOOOOOOEEEOOOOOFFFFFFFFFVVNNVVLLLLLLLAAAUGGGVVJJJANCCVVVIIWWWWWWWWWWWXXXXXXAEZZZZZWNNNNNNNRRRTTTTTTTYYYYYYYYYYSSKKKKKKKKKKLLLLLLLLLLL",
"DDDDDDDDOOOOOOEOEOOOOOFFFFFFFFFNNNNVLLLLLLLLLGGGGGGVGJJJJJJCVVIIWWWWWWWWWWWWXHHHUUUZZZZZZZUURNNNRRRRTTRTTRYYYYYYYYYYSSSSSSKKKKKKPPPLLLLLLLLL",
"DDDDVDDDOOOOOOOOOOOOOOOFFFFFFFNNNNGLLLLLLLLLLGGGGGGGGJJJJJJJVVIIWWWWWWWWWWHHHHHHHUUUUZZZZUUURRNRRRRRRRRRRRYYYYYYYYYYSSSSSSKKKKKKPPPPLLLLLLLL",
"DVVDVDDDOOOOOOOOOOOOOOOFFFFFNNNNNNGGLLLLLLLLGGGGGGGGGCCJJJJJDJPWWWWWWWWWHHHHHHHHUUUUUZZZZUUUURRRRRRRRRRRRRYYYYYYYYYSSSSSSSKKKKKPPPPPLLLLLLLL",
"DVVVVVDDOOOOOOOOOOOOOOOFZFFNNNNNNNNNLLLLLLLLLGGGGGGGGGGJJJJJJJPWWWWWWWWHHHHHHHHHUUUUUUUZUUUHCHHRRRRRRRRDDDXYYYYYSYSSSSSSSSKKKKPPPPPPPLLLLLLL",
"DVVVVVDOOOOOOOOOOOOOOONFNFFNNNNNNNNLLLLLLLLLGGGGGGGGGGGJJJJJJJJWWWWWWWWWWHHHHHHHHHHUUUZZUUUHHHHHHHRRDDDDDDDDYYYYSSSSSSSSSPPPPKPPPPPPPPPPLBLU",
"DVVVVVVVVVVOOOOVOOOOOONNNNFNNNNNNNNLLLLLLLLGGGGGGGGGGGGJJJJJJJJWWWWWWWWWWHHHHHHHHHUUUUUZUUUUHHHHHHRHDDDDDDDDYYYYYSSSSSSSSPPPPPPPPPPPPPPFPLLL",
"DVDVVVVVVVVOOOOVOOOOOVNNNNFNNNNNNNLLLLLLLLLGGGGGGGGGJJJJJJJJJJJJWWWWWWWWHHHHHHHHHHHUUUZZUUUUUUHHHHHHNNDDDDDDYYOYSSSSSSSSSPPPPPPPPPPPPPPPPXLL",
"DDDVVVDVVVVVVOVVOOOOOVNNNNNNNNNNNNNLLLLLLLLLLLGGGGGJJJJJJJJJJJJJWWWWWWWHHHHHHHHHHHHUUUZUUUUUUUSSHAAANNDDDDDDDDSSSSSSSSSPPPPPPPPPPPPPPPPPPXXX",
"DDVVVDDDVVVVVVVVVVOOOVNNNNNNNNNNNNNLLLLLLLLLLLLGGJJJJJJJJJJJJJJJJWWWWWWHHHHHHHHHHHHHUUUUUUUAAUAAAAAANNNDDDDDDDDSSSSSSSSPPPPPPPPPPPPPPPPPPXXX",
"DDVVVDDVVVVVVVVVVVVOOVNNNNNNNNNNNNLLLLLLLLLLLLLGLLUJJJJJJJJJJJOJJWWLWLWHHHHHHHHHHHHHUUUUUAAAAAAAAAAANNNDDDDDDSSSSSSSSSSSSPPPPPPPPPPPPPPXPPXX",
"DDDVVDDDDVVVVVVVVVVVOVVNNNNNNNNNNNLLLLLLLLLLLLLLLUUJAJAJJJJJJJJLLLLLLLWYYHHHHHHHHHHUUUUUUAAAAAAAAAAANNNDDDDDDDSSSSSSSSSSPPPPPPPPPPPPPPPXXXXX",
"DDDDDDDVVVVVVVVVVVVVVVVNNHNNNNNNLLLLLLLLLLLLLLLLLLUJAAAAJJHJJJLLLLLLLLWWYHHHHHHHHHHUUUUUUUAAAAAAAAAANNDDDDDDDDDSSSSSSTTSPPPPPPPPPPPPPPPXXXXX"
];

$CY = count($dat);
$CX = strlen($dat[0]);

$regions = [];
$seen = [];

// Helper to check if a coordinate has been seen
function seen_contains(&$seen, $x, $y) {
    return isset($seen["$x,$y"]);
}

// Mark a coordinate as seen
function seen_add(&$seen, $x, $y) {
    $seen["$x,$y"] = true;
}

// Flood fill (BFS) to find one region
function doregion($startX, $startY, &$dat, &$seen, $CX, $CY, &$regions) {
    $c = $dat[$startY][$startX];
    $todo = [[$startX, $startY]];
    $region = [];
    while (!empty($todo)) {
        list($x, $y) = array_shift($todo);
        if (seen_contains($seen, $x, $y)) {
            continue;
        }
        seen_add($seen, $x, $y);
        $region["$x,$y"] = true;
        $neighbors = [
            [$x+1, $y],
            [$x-1, $y],
            [$x, $y+1],
            [$x, $y-1]
        ];
        foreach ($neighbors as [$nx, $ny]) {
            if ($nx >= 0 && $ny >= 0 && $nx < $CX && $ny < $CY && $dat[$ny][$nx] == $c) {
                if (!seen_contains($seen, $nx, $ny)) {
                    $todo[] = [$nx, $ny];
                }
            }
        }
    }
    $regions[] = [$c, $region];
}

// Identify all regions
for ($y = 0; $y < $CY; $y++) {
    for ($x = 0; $x < $CX; $x++) {
        if (!seen_contains($seen, $x, $y)) {
            doregion($x, $y, $dat, $seen, $CX, $CY, $regions);
        }
    }
}

function perimeter($region) {
    // region is a set of coordinates "x,y"
    $n = 0;
    foreach ($region as $key => $val) {
        list($x, $y) = explode(",", $key);
        $x = (int)$x; $y = (int)$y;
        $neighbors = [
            [$x+1, $y],
            [$x-1, $y],
            [$x, $y+1],
            [$x, $y-1]
        ];
        foreach ($neighbors as [$nx, $ny]) {
            if (!isset($region["$nx,$ny"])) {
                $n += 1;
            }
        }
    }
    return $n;
}

function price($region) {
    return perimeter($region) * count($region);
}

function perimeter2($region) {
    $n = 0;
    foreach ($region as $key => $val) {
        list($x, $y) = explode(",", $key);
        $x = (int)$x; $y = (int)$y;
        // The neighbors and the additional checks 
        // For each direction, we also check (x1,y1) and (x2,y2)
        $checks = [
            [$x+1, $y, $x, $y-1, $x+1, $y-1],
            [$x-1, $y, $x, $y-1, $x-1, $y-1],
            [$x, $y+1, $x-1, $y, $x-1, $y+1],
            [$x, $y-1, $x-1, $y, $x-1, $y-1],
        ];
        foreach ($checks as [$nx, $ny, $x1, $y1, $x2, $y2]) {
            $in_nxy = isset($region["$nx,$ny"]);
            $in_x1y1 = isset($region["$x1,$y1"]);
            $in_x2y2 = isset($region["$x2,$y2"]);
            // if (nx,ny) not in region and not ((x1,y1) in region and (x2,y2) not in region):
            if (!$in_nxy && !( $in_x1y1 && !$in_x2y2 )) {
                $n += 1;
            }
        }
    }
    return $n;
}

function price2($region) {
    return perimeter2($region) * count($region);
}

// Compute and print sums
$total_price = 0;
foreach ($regions as [$c, $r]) {
    $total_price += price($r);
}
echo $total_price . "\n";

$total_price2 = 0;
foreach ($regions as [$c, $r]) {
    $total_price2 += price2($r);
}
echo $total_price2 . "\n";

?>

